apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: v1
    service: api
spec:
  containers:
    - name: api
      image: streaktracking_api
      imagePullPolicy: Never 
      ports:
        - name: api
          containerPort: 80
      env:
      - name:  ASPNETCORE_ENVIRONMENT
        value: Development
      - name: ConnectionString
        value: Server=postgres; Port=5432; Database=StreaksDb; User Id=admin; Password=admin1234;
      - name: EventBusConnection
        value: amqp://guest:guest@rabbitmq:5672