apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: v1
    service: database
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin1234
        - name: POSTGRES_DB
          value: StreaksDb                 
      ports:
        - containerPort: 5432