apiVersion: v1
kind: Pod
metadata:
  name: eventhandler
  labels:
    app: v1
    service: service-worker
spec:
  containers:
    - name: event-handler
      image: streaktracking_event_handler
      imagePullPolicy: Never 
      env:
      - name:  ASPNETCORE_ENVIRONMENT
        value: Development
      - name: ConnectionString
        value: Server=postgres; Port=5432; Database=StreaksDb; User Id=admin; Password=admin1234;
      - name: EventBusConnection
        value: amqp://guest:guest@rabbitmq:5672

