apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: v1
    service: frontend
spec:
  containers:
    - name: website
      image: website
      imagePullPolicy: Never 
      ports:
        - containerPort: 80