apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: v1
      service: messages
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: v1
        service: messages
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.10-management
          ports:
            - containerPort: 5672
            - containerPort: 15672  