apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-service
spec:
  type: NodePort
  ports:
    - targetPort: 15672
      port: 15672
      nodePort: 30009
  selector:
    app: v1
    service: messages