apiVersion: v1
kind: Service
metadata:
  name: website-service

spec:
   type: NodePort
   ports:
     - targetPort: 80
       port: 80
       nodePort: 30008
   selector:
     service: frontend
     app: v1
